- Production|Iron and Steel|{Iron Commodity}:
    description: Production of {Iron Commodity}
    unit: Mt
    tier: "{Iron Commodity}"

- Production|Non-Metallic Minerals|{Non-Metallic Minerals Commodity}:
    description: Production of {Non-Metallic Minerals Commodity}
    unit: Mt
    tier: "{Non-Metallic Minerals Commodity}"

- Production|Non-Ferrous Metals|{Non-Ferrous Metals Commodity}:
    description: Production of {Non-Ferrous Metals Commodity}
    unit: Mt
    tier: "{Non-Ferrous Metals Commodity}"

- Production|Chemicals|{Chemicals Commodity}:
    description: Production of {Chemicals Commodity}
    unit: Mt
    tier: "{Chemicals Commodity}"

- Production|Pulp and Paper|{Pulp and Paper Commodity}:
    description: Production of {Pulp and Paper Commodity}
    unit: Mt
    tier: "{Pulp and Paper Commodity}"
