- Production|{Industry-Sector}|{Production Unit}:
    description: Production of industrial commodities by sector
    unit: Mt/yr

- Production|Iron and Steel|{Iron Commodity}|{Production Unit}:
    description: Production of steel commodities
    unit: Mt/yr
- Production|Non-Metallic Minerals|{Non-Metallic Minerals Commodity}|{Production Unit}:
    description: Production of mineralic commodities
    unit: Mt/yr
- Production|Non-Ferrous Metals|{Non-Ferrous Metals Commodity}|{Production Unit}:
    description: Production of non ferrous metals
    unit: Mt/yr
- Production|Chemicals|{Chemicals Commodity}|{Production Unit}:
    description: Production of chemical commodities
    unit: Mt/yr
- Production|Pulp and Paper|{Pulp and Paper Commodity}|{Production Unit}:
    description: Production of paper commodities
    unit: Mt/yr
