- Price|Production|Iron and Steel|{Iron Commodity}:
    description: Price of {Iron Commodity}
    unit: USD_2010/Mt
    tier: "{Iron Commodity}"
    weight: Production|Iron and Steel|{Iron Commodity}
    navigate: Price|Industry|Iron and Steel|{Iron Commodity}
    engage: Price|Industry|Iron and Steel|{Iron Commodity}

- Price|Production|Non-Metallic Minerals|{Non-Metallic Minerals Commodity}:
    description: Price of {Non-Metallic Minerals Commodity}
    unit: USD_2010/Mt
    tier: "{Non-Metallic Minerals Commodity}"
    weight: Production|Non-Metallic Minerals|{Non-Metallic Minerals Commodity}
    navigate: Price|Industry|Non-Metallic Minerals|{Non-Metallic Minerals Commodity}
    engage: Price|Industry|Non-Metallic Minerals|{Non-Metallic Minerals Commodity}

- Price|Production|Non-Ferrous Metals|{Non-Ferrous Metals Commodity}:
    description: Price of {Non-Ferrous Metals Commodity}
    unit: USD_2010/Mt
    tier: "{Non-Ferrous Metals Commodity}"
    weight: Production|Non-Ferrous Metals|{Non-Ferrous Metals Commodity}
    navigate: Price|Industry|Non-Ferrous Metals|{Non-Ferrous Metals Commodity}
    engage: Price|Industry|Non-Ferrous Metals|{Non-Ferrous Metals Commodity}

- Price|Production|Chemicals|{Chemicals Commodity}:
    description: Price of {Chemicals Commodity}
    unit: USD_2010/Mt
    tier: "{Chemicals Commodity}"
    weight: Production|Chemicals|{Chemicals Commodity}
    navigate: Price|Industry|Chemicals|{Chemicals Commodity}
    engage: Price|Industry|Chemicals|{Chemicals Commodity}
