- Production|Iron and Steel|{Iron Commodity}:
    description: Production of {Iron Commodity}
    unit: Mt/yr
    tier: 2
    navigate: Production|Iron and Steel|{Iron Commodity}|Volume
    engage: Production|Iron and Steel|{Iron Commodity}|Volume
    ngfs5: Production|{Iron Commodity}

- Production|Non-Metallic Minerals|{Non-Metallic Minerals Commodity}:
    description: Production of {Non-Metallic Minerals Commodity}
    unit: Mt/yr
    tier: 2
    navigate: Production|Non-Metallic Minerals|{Non-Metallic Minerals Commodity}|Volume
    engage: Production|Non-Metallic Minerals|{Non-Metallic Minerals Commodity}|Volume
    ngfs5: Production|{Non-Metallic Minerals Commodity}

- Production|Non-Ferrous Metals|{Non-Ferrous Metals Commodity}:
    description: Production of {Non-Ferrous Metals Commodity}
    unit: Mt/yr
    tier: 2
    navigate: Production|Non-Ferrous Metals|{Non-Ferrous Metals Commodity}|Volume
    engage: Production|Non-Ferrous Metals|{Non-Ferrous Metals Commodity}|Volume

- Production|Chemicals:
    description: Production of the chemicals sector excluding feedstocks
    unit: Mt/yr
    tier: 2
- Production|Chemicals|{Chemicals Commodity}:
    description: Production of {Chemicals Commodity}
    unit: Mt/yr
    tier: 2
    navigate: Production|Chemicals|{Chemicals Commodity}|Volume
    engage: Production|Chemicals|{Chemicals Commodity}|Volume

- Production|Pulp and Paper|{Pulp and Paper Commodity}:
    description: Production of {Pulp and Paper Commodity}
    unit: Mt/yr
    tier: 2
