# This workflow validates that (new) variables are not referenced as deprecated legacy variables
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Validate the project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

jobs:
  project-validation:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Install pytest
      run: pip install pytest

    - name: Run the legacy validation
      run: pytest tests/test_legacy.py
